from api.core.models import NodeLoginCredentials as NodeLoginCredentials
from typing import Any

node_router: Any

async def register_node() -> None: ...
async def login_node(credentials: NodeLoginCredentials): ...
async def get_chain_info() -> None: ...
async def pre_post_negotiate(phase_state: Union[str, None] = ...): ...
async def process_negotiate() -> None: ...
