from api.core.models import DashboardContext, IssueToStudentIn as IssueToStudentIn, NewStudentIn as NewStudentIn, UserLoginIn as UserLoginIn, UserLogoutIn as UserLogoutIn
from typing import Any
from utils.constants import AddressUUID as AddressUUID

dashboard_router: Any

async def get_data_to_dashboard(context: DashboardContext): ...
async def login_user(credentials: UserLoginIn): ...
async def logout_user(to_invalidate: UserLogoutIn): ...
async def get_applicants(applicant_count: Union[int, None] = ..., page: Union[int, None] = ...): ...
async def get_applicant(applicant_id: AddressUUID): ...
async def get_all_requests() -> None: ...
async def get_request(request_id: int): ...
async def request_document_view(request_id: int, doc_type: str): ...
async def get_issuances(issuance_count: Union[int, None] = ..., page: Union[int, None] = ...): ...
async def get_issued_docs(issue_id: int): ...
async def mint_document(doc_context: IssueToStudentIn): ...
async def get_students(student_count: Union[int, None] = ..., page: Union[int, None] = ...): ...
async def get_student(student_addr: AddressUUID): ...
async def create_student(student_context: NewStudentIn): ...
