name: Folioblocks Web, Build and Deploy
on:
  push:
    branches:
      - latest
    paths:
      - "web/**"

  workflow_dispatch:

jobs:
  folioblocks-web:
    name: Folioblocks Web Builder and Deployer
    runs-on: ubuntu-latest

    steps:
      - name: Step 0 | Repository Checkout
        uses: actions/checkout@v3

      - name: Step 1 | Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # # From my own repository, https://github.com/CodexLink/discord-activity-badge.
      - name: Step 2 | Load and Save Container Layer Cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # # From https://stackoverflow.com/questions/58482655/what-is-the-closest-to-npm-ci-in-yarn
      - name: Step 3 | Remove Modules & Install Packages from Yarn
        run: |
          cd web && yarn install

      - name: Step 4 | Build Folioblocks-Web
        run: cd web && yarn build

      - name: Step 5 | Deploy from `gh-pages`
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: web/dist/spa
